<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spem20BasePluginProfile" nsURI="http:///spem20BasePluginProfile.ecore"
    nsPrefix="spem20BasePluginProfile">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="SPEM 2.0 Base Plugin Profile"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="WorkProductRelationshipKind" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseAssociation" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Association">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="base_Association"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImpactedBy" eSuperTypes="#//WorkProductRelationshipKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//WorkProductRelationshipKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Primary" eSuperTypes="#//PerformerKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="PerformerKind" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseAssociation" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Association">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="base_Association"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Additional" eSuperTypes="#//PerformerKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assisting" eSuperTypes="#//PerformerKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="WorkProductKind" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseClass" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Class">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="base_Class"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="#//WorkProductKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deliverable" eSuperTypes="#//WorkProductKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Outcome" eSuperTypes="#//WorkProductKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="CategoryKind" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseClass" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Class">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="base_Class"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Discipline" eSuperTypes="#//CategoryKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//ActivityKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityKind" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseClassifier" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Classifier">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="base_Classifier"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessPattern" eSuperTypes="#//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeliveryProcess" eSuperTypes="#//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="Iteration" eSuperTypes="#//ActivityKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Phase" eSuperTypes="#//ActivityKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregation" eSuperTypes="#//WorkProductRelationshipKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Checklist" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="GuidanceKind" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseClass" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Class">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="base_Class"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concept" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Estimate" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="EstimationConsiderations" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Example" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Guideline" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Practice" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Report" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReusableAsset" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="SupportingMaterial" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Template" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="TermDefinition" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="ToolMentor" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Whitepaper" eSuperTypes="#//GuidanceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoleSet" eSuperTypes="#//CategoryKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="#//CategoryKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="ToolCategory" eSuperTypes="#//CategoryKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessPlanningTemplate" eSuperTypes="#//Process"/>
</ecore:EPackage>
